mvc01/Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace mvc01.Models
{
    public class User
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Key]
        [EmailAddress]
        [Required]
        [Display(Name = "Email address: ")]
        public string Email { get; set; }

        public string Username { get; set; }

        [Display(Name = "Password: ")] 
        [Required]
        [DataType(DataType.Password)]
        [StringLength(200, MinimumLength=6)]
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public byte[] ProfilePicture { get; set; }

        public User GetUser(int id)
        {
            if (ID == id)
                return this;

            return null;
        }
        
    }
}

mvc01/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvc01.Hubs;

namespace mvc01.Controllers
{
    public class ChatController : Controller
    {
        // GET: Chat
        public ActionResult Index()
        {
            var name = TempData["username"];
            return View(name);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection form)
        {

            var username = form["username"];
            TempData["username"] = username;

            var chat = new ChatHub();

            if (String.IsNullOrEmpty(username))
            {
                ViewBag.Message = "Please insert a valid username";
                return View(form);
            }

            if (chat.IsUsernameTaken(username))
            {
                return RedirectToAction("Index");
            }

            ViewBag.Message = "Username is already taken";
            return View(form);
        }
    }
}

mvc01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc01.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

mvc01/Controllers/UsersController.cs
using System.Linq;
using System.Web.Mvc;
using mvc01.DAL;
using mvc01.Models;
using System.Web.Security;
using System.Web;
using System;

namespace mvc01.Controllers
{
    public class UsersController : Controller
    {
        private UsersDBContext db = new UsersDBContext();

        // GET: Users
        public ActionResult Info()
        {
            return View(db.Users.ToList());
        }

        [HttpGet]
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(User user)
        {
            if (ModelState.IsValid)
            {
                if (IsValid(user.Email, user.Password))
                {
                    using (var db = new UsersDBContext())
                    {
                        string username = db.Users.FirstOrDefault(u => u.Email == user.Email).Username;
                        FormsAuthentication.SetAuthCookie(username, false);
                    }

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Please check log in information");
                }
            }
            return View(user);
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult Edit(HttpPostedFileBase image)
        {
            if(image != null)
            {
                using(db)
                {
                    string username = System.Web.HttpContext.Current.User.Identity.Name;

                    User user = db.Users.Where(u => u.Username == username).Single();

                    user.ProfilePicture = new byte[image.ContentLength];
                    image.InputStream.Read(user.ProfilePicture, 0, image.ContentLength);

                    db.Entry(user).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult GetProfileImage()
        {
            using (db)
            {
                string username = System.Web.HttpContext.Current.User.Identity.Name;

                User user = db.Users.Where(u => u.Username == username).Single();

                return File(user.ProfilePicture, "image/png");
            }
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(User user)
        {
            if (ModelState.IsValid)
            {
                var count = db.Users.Count(u => u.Email == user.Email);

                if (count != 0)
                {
                    ModelState.AddModelError("", "Email already registered");
                }
                else
                {
                    using (db)
                    {
                        var crypto = new SimpleCrypto.PBKDF2();

                        var users = db.Users.Create();

                        users.Email = user.Email;
                        users.Password = crypto.Compute(user.Password);
                        users.Username = user.Username;
                        users.PasswordSalt = crypto.Salt;


                        db.Users.Add(users);
                        db.SaveChanges();

                        return RedirectToAction("LogIn", "Users");
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "Please check registration fields");
            }
            return View(user);
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        private bool IsValid(string email, string password)
        {
            bool isValid = false;

            var crypto = new SimpleCrypto.PBKDF2();

            using (db)
            {
                var user = db.Users.FirstOrDefault(e => e.Email == email);

                if (user != null)
                {
                    if (user.Password == crypto.Compute(password, user.PasswordSalt))
                    {
                        isValid = true;
                    }
                }

            }

            return isValid;
        }
    }
}

mvc01/Views/Chat/Index.cshtml
@model string

@{
    ViewBag.Title = "Index";
}

<script>
    var redirectoToLogin = '@Url.Action("Login", "Chat")';
</script>

@Styles.Render("~/Content/ChatStyle.css")
<div id="wrapper">
    <div id="music">
        <img src="https://cdn0.iconfinder.com/data/icons/super-mono-reflection/blue/button-play_blue.png" id="playbtn" />
        <div id="player"></div>
        <ul id="results" style="list-style-type:none">
            <li><h1>&times;</h1></li>
        </ul>
    </div>
    <div id="chat-container">
        <div id="dynamic-content">
            <div class="channel global">Global Chat</div>
        </div>
        <input type="hidden" id="nickname" value="@Model" />               <!-- Text field for nickname (?) -->
        <div id="msg-container">
            <!-- Contains text field and messages -->
            <div id="messages">
                <ul id="global" class="msgcont"></ul>               <!-- Place where messages are stored -->
            </div>
            <textarea spellcheck="false" id="message" class="messagebox"></textarea>                           <!-- Text field -->
            
        </div>
        <div id="onlineusers-content">
            <div id="onlineusers">
                <!-- Online users -->
                <b>Online Users</b>
            </div>
            <select id="users">
                <!--Userlist which is used to add to channel chat-->
            </select>
        </div>
    </div>
    <style>
    </style>
    @section scripts
    {
        @Scripts.Render("~/Scripts/jquery-2.1.3.js")
        @Scripts.Render("~/Scripts/jquery-ui.min.js")
        @Scripts.Render("~/Scripts/jquery.signalR-2.2.0.min.js")
        @Scripts.Render("~/signalr/hubs")
        @Scripts.Render("//connect.soundcloud.com/sdk.js")
        
        @Scripts.Render("~/Scripts/Custom/chat.js")
        @Scripts.Render("~/Scripts/Custom/display.js")
        @Scripts.Render("~/Scripts/Custom/soundcloud.js")

        
    }
</div>

mvc01/Views/Chat/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
<h2>Login</h2>
<h2>Login</h2>
<h2>Login</h2>

@using (Html.BeginForm("Login", "Chat", FormMethod.Post))
{
    if (ViewBag.Message != null)
    {
        <span>@ViewBag.Message</span><br />
    }

    @Html.Label("Name: ");
    @Html.TextBox("username");
    <input type="submit" value="Login" />
}

mvc01/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

mvc01/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

mvc01/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div id="banner">
    <img src="@Url.Content("~/Content/Images/banner.jpeg")" />
</div>
<div id="content">

</div>

mvc01/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Home</title>
    @Styles.Render("~/Content/edit.css")
    @Styles.Render("~/Content/css.css")
    <link href='http://fonts.googleapis.com/css?family=Quicksand:400' rel='stylesheet' type='text/css'>
</head>

<body>
    <div class="header">
        <div id="container">
            <ul class="menu-left">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            <ul class="menu-right">
                @if (Request.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Log out", "LogOut", "Users")</li>

                    <li id="profile-picture"><div id="profile-picture-wrapper"><img src='@Url.Action("GetProfileImage", "Users")' alt="Can not be displayed" width="30" height="30" />                   </div></li>
                    <li id="username-nav">@Html.Raw("Welcome, " + HttpContext.Current.User.Identity.Name)</li>
                }
                else
                {
                    <li>@Html.ActionLink("Register", "Register", "Users")</li>
                    <li>@Html.ActionLink("Log in", "Login", "Users")</li>
                }
            </ul>
        </div>
    </div>
    <div class="body-content">
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

mvc01/Views/Users/Edit.cshtml
@model mvc01.Models.User

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div id="upload-container">
    <div id="upload-image">
        @using (Html.BeginForm("Edit", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div>@Html.LabelFor(u => u.ProfilePicture)</div>
            <input type="file"  name="Image"/>
            <input type="submit" value="Upload" />
        }
    </div>
    <div>
        <img src='@Url.Action("GetProfileImage", "Users")' alt="Can not be displayed" width="40" height="40" />
    </div>
</div>

mvc01/Views/Users/Info.cshtml
@model IEnumerable<mvc01.Models.User>

@{
    ViewBag.Title = "Users info";
}

<h2>Users database info</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PasswordSalt)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PasswordSalt)
        </td>
    </tr>
}

</table>

mvc01/Views/Users/LogIn.cshtml
@model mvc01.Models.User

@{
    ViewBag.Title = "Log in";
}

<h2></h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "Your email or password is incorrect");
    <div>
        <fieldset>
            <legend>Login:</legend>
            <div>@Html.LabelFor(u => u.Email)</div> 
            <br />

            <div>
                @Html.TextBoxFor(u => u.Email)
                @Html.ValidationMessageFor(u => u.Email)
            </div> 
            <br />

            <div>@Html.LabelFor(u => u.Password)</div>
            <br />

            <div>
                @Html.PasswordFor(u => u.Password)
                @Html.ValidationMessageFor(u => u.Password)
            </div>
            <br />
            
            <input type="submit" value="Log in" />
            <br />

        </fieldset>
    </div>
}

mvc01/Views/Users/Register.cshtml
@model mvc01.Models.User

@{
    ViewBag.Title = "Register";
}

<h2></h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "Registration failed");
    <div>
        <fieldset>
            <legend>Register:</legend>

            <div>@Html.LabelFor(u => u.Email)</div>

            <div>
                @Html.TextBoxFor(u => u.Email)
                @Html.ValidationMessageFor(u => u.Email)
            </div>

            <div>@Html.LabelFor(u => u.Username)</div>

            <div>
                @Html.TextBoxFor(u => u.Username)
                @Html.ValidationMessageFor(u => u.Username)
            </div>

            <div>@Html.LabelFor(u => u.Password)</div>

            <div>
                @Html.PasswordFor(u => u.Password)
                @Html.ValidationMessageFor(u => u.Password)
            </div>
            <br />

            <input type="submit" value="Register" />

        </fieldset>
    </div>
}